-- MySQL Script generated by MySQL Workbench
-- Sat Jan 22 17:18:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table software
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS software (
  id SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  onlySubject BOOLEAN NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table client
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS client (
  id SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  cif VARCHAR(45) UNIQUE NOT NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table client_keywords
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS client_keywords (
  id SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  idClient INT NOT NULL,
  PRIMARY KEY (id, idClient),
  CONSTRAINT fk_client_identifiers_clients
    FOREIGN KEY (idClient)
    REFERENCES client (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

-- -----------------------------------------------------
-- Table software_keywords
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS software_keywords (
  id SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  idSoftware INT NOT NULL,
  PRIMARY KEY (id, idSoftware),
  CONSTRAINT fk_software_identifiers_software
    FOREIGN KEY (idSoftware)
    REFERENCES software (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table success_keywords
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS success_keywords (
  id SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  idSoftware INT NOT NULL,
  PRIMARY KEY (id, idSoftware),
  CONSTRAINT fk_success_keywords_software1
    FOREIGN KEY (idSoftware)
    REFERENCES software (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table error_keywords
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS error_keywords (
  id SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  idSoftware INT NOT NULL,
  PRIMARY KEY (id, idSoftware),
  CONSTRAINT fk_error_keywords_software1
    FOREIGN KEY (idSoftware)
    REFERENCES software (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table warning_keywords
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS warning_keywords (
  id SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  idSoftware INT NOT NULL,
  PRIMARY KEY (id, idSoftware),
  CONSTRAINT fk_warning_keywords_software1
    FOREIGN KEY (idSoftware)
    REFERENCES software (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table Usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Usuario (
  id SERIAL NOT NULL,
  email_login VARCHAR(45) UNIQUE NOT NULL,
  passw VARCHAR(255) NOT NULL,
  login BOOLEAN NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table usuario_email
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario_email (
  id SERIAL NOT NULL,
  email VARCHAR(45) NULL,
  idUsuario INT NOT NULL,
  PRIMARY KEY (id, idUsuario),
  CONSTRAINT fk_user_email_users1
    FOREIGN KEY (idUsuario)
    REFERENCES Usuario (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table usuario_client
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario_client (
  idUsuario INT NOT NULL,
  idClient INT NOT NULL,
  PRIMARY KEY (idUsuario, idClient),
  CONSTRAINT fk_users_has_clients_users1
    FOREIGN KEY (idUsuario)
    REFERENCES Usuario (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_users_has_clients_clients1
    FOREIGN KEY (idClient)
    REFERENCES client (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table mail
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mail (
  id SERIAL NOT null PRIMARY KEY,
  status TEXT NULL,
  messageId TEXT UNIQUE NOT NULL,
  from_mail TEXT NOT NULL,
  subject TEXT NOT NULL,
  text_mail TEXT NULL,
  html TEXT NULL,
  date TIMESTAMP NULL,
  idSoftware INT,
  idClient INT,
  sended BOOLEAN NULL,
  CONSTRAINT fk_mail_software1
    FOREIGN KEY (idSoftware)
    REFERENCES software (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_mail_client1
    FOREIGN KEY (idClient)
    REFERENCES client (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

-- -----------------------------------------------------
-- Table usuario_send_interval
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario_send_interval (
  id SERIAL NOT NULL,
  date TIMESTAMP NULL,
  idUsuario INT NOT NULL,
  PRIMARY KEY (id, idUsuario),
  CONSTRAINT fk_user_send_interval_user1
    FOREIGN KEY (idUsuario)
    REFERENCES Usuario (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

